#!/bin/bash

# Terminate already running bar instances
killall -q redshiftgui.elf

# Wait until the processes have been shut down
while pgrep -u $UID -x redshiftgui >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
redshiftgui --min &
